version: "3.9"

networks:
  bank:
    driver: bridge
volumes:
   mysql:
     driver: local
   bank-rabbit-data:
       driver: local

services:
  nginx:
    image: nginx:1.23.4
    container_name: bank_system_nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8002:8000"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - bank

  mysql:
    platform: linux/amd64
    image: mysql
    container_name: bank_system_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bank_system
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
    networks:
      - bank

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_system_php
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - bank

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:3.11.28-management
    container_name: bank_system_rabbitmq
    restart: always
    ports:
      - 5673:5672
      - 15673:15672  # Change the first port number to your desired host port for management UI
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
        - bank-rabbit-data:/var/lib/rabbitmq
    networks:
      - bank

  redis:
    image: redis:6.2
    container_name: bank_system_redis
    restart: unless-stopped
    ports:
        - "6380:6379"
    networks:
        - bank
